# Generated by Django 6.0.2 on 2026-02-14 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('categories', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('media_format', models.CharField(blank=True, max_length=100)),
                ('scraped_on', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='palestras.author')),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mp3_url', models.URLField(max_length=500)),
                ('local_path', models.FileField(blank=True, max_length=500, upload_to='audios')),
                ('downloaded', models.BooleanField(default=False)),
                ('transcription', models.TextField(blank=True)),
                ('transcription_method', models.CharField(blank=True, max_length=100)),
                ('transcribed_on', models.DateTimeField(blank=True, null=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='palestras.palestra')),
            ],
        ),
    ]
