# Generated by Django 6.0.2 on 2026-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='transcription_timecoded',
            field=models.TextField(blank=True),
        ),
    ]
