# Generated by Django 6.0.2 on 2026-02-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0002_audiotrack_transcription_timecoded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='concepts',
            field=models.ManyToManyField(blank=True, to='palestras.concept'),
        ),
    ]
