# Generated by Django 6.0.2 on 2026-02-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0003_concept_audiotrack_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotrack',
            name='concepts',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='concepts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
