# Generated by Django 6.0.2 on 2026-03-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0004_remove_audiotrack_concepts_delete_concept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='author_photos'),
        ),
    ]
