# Generated by Django 6.0.2 on 2026-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0005_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wikipedia_search',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
