# Generated by Django 6.0.2 on 2026-03-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0006_author_wikipedia_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotrack',
            name='downloaded',
        ),
    ]
