# Generated by Django 6.0.2 on 2026-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0007_remove_audiotrack_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotrack',
            name='local_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='audios'),
        ),
    ]
