# Generated by Django 6.0.2 on 2026-03-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0008_alter_audiotrack_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
